// Generated by CoffeeScript 1.6.3
(function() {
  var TestModel, history, m, secondSaveCalled, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  history = [];

  secondSaveCalled = false;

  Backbone.sync = function(method, model, options) {
    var _this = this;
    return setTimeout(function() {
      console.log('timedout');
      history.push(model.val);
      return options.success(model, {}, options);
    }, 100);
  };

  TestModel = (function(_super) {
    __extends(TestModel, _super);

    function TestModel() {
      _ref = TestModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TestModel.prototype.initialize = function() {};

    return TestModel;

  })(Backbone.Model);

  m = new TestModel;

  m.val = 100;

  m.save({}, {
    success: function() {
      var _this = this;
      return test("First value saved", function() {
        ok(history.length === 1, "First call is saved");
        m.val = 200;
        m.save({}, {
          success: function() {
            return secondSaveCalled = true;
          }
        });
        m.val = 300;
        return m.save({}, {
          success: function() {
            var _this = this;
            return test("Third call is saved", function() {
              ok(secondSaveCalled === false, "Second call never executed");
              return ok(history.length === 2, "Call 2 times");
            });
          }
        });
      });
    }
  });

}).call(this);

/*
//@ sourceMappingURL=save.map
*/
