// Generated by CoffeeScript 1.6.3
(function() {
  Backbone.Model.prototype.original_save = Backbone.Model.prototype.save;

  Backbone.Model.prototype.save = function(key, val, options) {
    var dequeue, error, success,
      _this = this;
    if (!this._requestQueue) {
      this._requestQueue = [];
    }
    this._requestQueue.push({
      key: key,
      val: val,
      options: options
    });
    if (this._requestQueue.length > 1) {
      return null;
    }
    if (key === null || typeof key === 'undefined' || typeof key === 'object') {
      options = val;
    }
    if (!options) {
      options = {};
    }
    success = options.success;
    error = options.error;
    dequeue = function() {
      var length, param;
      param = _.last(_this._requestQueue);
      length = _this._requestQueue.length;
      _this._requestQueue = [];
      if (length > 1) {
        return _this.save(param.key, param.val, param.options);
      }
    };
    options.success = function(model, resp, options) {
      if (success) {
        success(model, resp, options);
      }
      return dequeue();
    };
    options.error = function(model, resp, options) {
      if (error) {
        error(model, resp, options);
      }
      return dequeue();
    };
    if (key === null || typeof key === 'undefined' || typeof key === 'object') {
      val = options;
    }
    return this.original_save(key, val, options);
  };

}).call(this);

/*
//@ sourceMappingURL=serialize_backbone_model.map
*/
